/* ==========================================
 * TABLE: GCG_5263_MAT_SHORT
 * ========================================== */
CREATE TABLE "GCG_5263_MAT_SHORT"(
 "PART" CHAR(20) NOT NULL ,
 "DESCRIPTION" CHAR(30) NOT NULL ,
 "UM" CHAR(2) NOT NULL ,
 "QTY_REQ" NUMERIC(8,2) NOT NULL ,
 "QTY_ONHAND" NUMERIC(8,2) NOT NULL ,
 "QTY_OLDREV" NUMERIC(8,2),
 "PO_NUMBER" CHAR(7),
 "PO_DUE" CHAR(10),
 "PO_QTY_ORD" NUMERIC(8,2),
 "PO_QTY_RCVD" NUMERIC(8,2),
 "PO_VENDOR" CHAR(30),
 "TERMINAL" CHAR(6) NOT NULL ,
 "WORK_ORDER" CHAR(6) NOT NULL ,
 "WORK_ORDER_SUFFIX" CHAR(3) NOT NULL ,
 "WO_DUEDATE" CHAR(10),
 "WO_DESC" CHAR(30),
 "WO_PART" CHAR(20),
 "WO_JOB_SUFFIX" CHAR(9));


